### PR TITLE
[ready for EOWG review/approval] integrated decription more prominent and clear

### PR DESCRIPTION
**Pull request by shawna-slh**
EOWG's [updated Requirements Analysis for 2021 January Revision](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#2021_January_Revision)  focuses on this scenario:
> I'm recording a video presentation for a remote conference (and I'm already a bit overwhelmed about it). What do I need to do for accessibility?

This pull request is a proposal for communicating to that user/scenario that they probably should do integrated description (while also addressing other users). This proposal simplifies some language and adds examples. See:

* **[Diff of markup](https://github.com/w3c/wai-media-guide/pull/157/files)**
* **[Preview of edited Introduction section of description page](https://deploy-preview-157--wai-media-guide.netlify.app/media/av/description/#introduction)**
* **[Preview of edited "Plan for audio description of visual information" section of AV Content page](https://deploy-preview-157--wai-media-guide.netlify.app/media/av/av-content/#plan-description)** _[added 14 Jan]_

Thoughts on these or other edits?

### CODE REVIEW

**Review by nitedog — APPROVED** [review]
Good changes!

**Comment by shawna-slh** [comment]
Shawn to do:
* [x] fill in links "(These videos are also available from @@non-YouTube links.)"

after finalized with EOWG:
* [ ] add to changelog!

**Review by bakkenb — APPROVED** [review]
+1 to changes.

**Comment by shawna-slh** [comment]
[Aproved in 15 Jan EOWG meeting](https://www.w3.org/2021/01/15-eo-minutes#t02)

**Pull request merged**
