### PR TITLE
quick tips as a separate page with DL

### PR DESCRIPTION
**Pull request by shawna-slh**
See: **[Quick Tips draft page](https://deploy-preview-143--wai-media-guide.netlify.app/media/av/quicktips/)**

EOWG, please comment below on things like:
* Pros and cons to having a page like this?
* Comments on this draft format, length, tone, etc.?
* Order of topics? (here it's more order of importance for those making videos; which is a different order from the [main resource](https://www.w3.org/WAI/media/av/#how-to-make-audio-and-video-accessible))
* What about sign language?
* Title ideas?

### CODE REVIEW

**Comment by iadawn** [comment]
* Pros and cons to having a page like this?

  Big pro: quick and simple list of things to think about
  Con: Some items may leave readers wondering - e.g. what does an accessible media player look like and where can I get one?
  Con: Doesn't align with the 'Tips' style but that might be addressed with a simple title change

* Comments on this draft format, length, tone, etc.?

  Seems about right too me. 

* Order of topics? (here it's more order of importance for those making videos; which is a different order from the main resource)

  I think this if fine, but I would probably suggest putting the planning point at the top. It seems like the first thing you would think of but it is tucked away. The others are fine in priority order.

* What about sign language?

  "Consider how you would provide sign language"

* Title ideas?

  "A/V Media accessibility checklist"
  "A/V Media accessibility quick reference"
  "Plan accessible A/V Media"
  "Quick guide to making A/V Media accessible"

**Comment by RealJoshue108** [comment]
@slhenry The general content is really good 👍 One thing that could be worth considering, I think the sections 'Does my media need x' which are found in the pages relating to Captions, Subtitles etc - could be moved to the end of these pages. 

I think moving these sections would improve legibility and comprehension, as those reading this content may already be primed and looking for a steer, so I think moving these sections to the end of each related page would help.

**Comment by shawna-slh** [comment]
Initial idea from [EOWG meeting 30 October](https://www.w3.org/2020/10/30-eo-minutes#item04)

Notes from from [EOWG meeting 20 November](https://www.w3.org/2020/11/20-eo-minutes#item07):
* quicktips good
* maybe change first page of resource to do that (and maybe ex-col other sections) (rather than separate quicktips page)

First pass at putting **[quicktips-like list in summary](https://deploy-preview-143--wai-media-guide.netlify.app/media/av/)**.

**Comment by iadawn** [comment]
+1 to the first pass!

**Comment by AndrewArch** [comment]
Love the 'quick tips' (but maybe a different name as suggested by others)

can we rephrase the line about not required for WCAG to more like the following to 'recommend' going beyond the WCAG requirement?
"What is needed to meet user needs, beyond WCAG. (If it doesn’t have any ‘A’, then it is not required in WCAG, **but strongly recommended**.)"

**Comment by shawna-slh** [comment]
in case preview disappears and we want to see this later:
image

**Pull request closed without merging**
