### PR TITLE
[EOWG approved] include text in description

### PR DESCRIPTION
**Pull request by shawna-slh**
Goal: Make more explicitly clear that text in video needs to be available in alternative format.

### CODE REVIEW

**Comment by bakkenb** [comment]
+1 to this additional text.

**Comment by shawna-slh** [comment]
Based on [EOWG 30 Oct input](https://www.w3.org/2020/10/30-eo-minutes#item04), added:
> , including text displayed in the video."

under https://deploy-preview-126--wai-media-guide.netlify.app/media/av/#how-to-make-audio-and-video-accessible
and under https://deploy-preview-126--wai-media-guide.netlify.app/media/av/av-content/#plan-description

Edit before the meeting had added to https://deploy-preview-126--wai-media-guide.netlify.app/media/av/description/#writing this paragraph:
> Generally, all text in the video should be included in the main audio (integrated description) or in the separate description. For example, title text at the beginning of the video, links and e-mail addresses shown at the end, speakers’ names in text, and text in a presentation. The text does not have to be included verbatim (exactly word-for-word), yet all of the information conveyed by the text needs to be available in the main audio, in the separate description, or clearly with the video.

**Review by nitedog — APPROVED** [review]

**Comment by lakeen** [comment]
+1

**Comment by sharronrush** [comment]
+1 to these changes

**Comment by eoncins** [comment]
+1

**Comment by shawna-slh** [comment]
approved in [https://www.w3.org/2020/11/20-eo-minutes#ResolutionSummary 20 Nov 2020 telecon]

**Comment by AndrewArch** [comment]
+1 to this change

**Pull request merged**
