### PR TITLE
Checklists style

### PR DESCRIPTION
**Pull request by yatil**

### CODE REVIEW

**Comment by yatil** [comment]
@slhenry If you are ok with this design, I’m happy to put that into the style guide:

https://deploy-preview-17--wai-media-guide.netlify.com/design-develop/media/planning/

**Comment by yatil** [comment]
@slhenry As per our Tuesday discussion:

* [x] White-ish background for header
* [x] Lighter color for the background
* [x] Border bottom on the header

Let me know what you think: https://deploy-preview-17--wai-media-guide.netlify.com/design-develop/media/planning/

**Comment by shawna-slh** [comment]
Thanks, Eric! Can we call it good for now (yet OK if we decide to tweak it later) ?

**Comment by yatil** [comment]
@slhenry If you can call it good for now, I can :-) I’ll put it into the style guide and the template and send in a pull request for the updated files early tomorrow.

**Comment by yatil** [comment]
Close this for #25

**Pull request closed without merging**
