### PR TITLE
Update submodule & change navigation.yml into symlink

### PR DESCRIPTION
**Pull request by remibetin**
@shawna-slh @SteveALee I suggest updating the submodule and using a symlink for the navigation.yml file (as in other repositories) to get a correct navigation in the Netlify preview.

We can see the differences in the menu here :
- My draft PR without this update https://deploy-preview-177--wai-media-guide.netlify.app/
- This PR with the update https://deploy-preview-178--wai-media-guide.netlify.app/

### CODE REVIEW

**Comment by SteveALee** [comment]
@remibetin CC @shawna-slh  

Absolutely! Thanks.

The only reason this has not been done is there are a few resource repos in the same state and we have an action to look into why. 

But, if as I suspect given your example previews, this is causing you a problem,we can easily merge your PR now.

There is a similar action to deal with submodule handling. FYI the submodules used for builds on netlfy or locally using "netlify build" are always the latest versions. The updated version is just not pushed to git for the resources. This is a workflow bug IMHO.

I can think of 3 possible explanations for having a local navigation.yml rather than using the latest shared version via the data submodule

- a simple bug
- was used for local dev but accidentality committed
- is supposed to diverge from the shared version - but this will soon get out of date.

@shawna-slh let me know if you'd like me to look at this issue for all repos some time soon. I'm happy to merge the PR.

**Review by SteveALee — APPROVED** [review]
Looks good. No other actions are required in this case.

**Comment by remibetin** [comment]
Thanks for your answer @SteveALee !

Indeed, I have no problem locally because I launch this command `git submodule update --remote` before serving Jekyll. 
I need this update in the repository only to facilitate reviews from other translators who will only look at the Netlify preview of my PR.

Actually the local navigation.yml file was part of the initial commit 098dbc8909b07cb8674c55023eee58a7a2059289

**Comment by SteveALee** [comment]
@remibetin 

> Indeed, I have no problem locally because I launch this command `git submodule update --remote` before serving Jekyll.
> I need this update in the repository only to facilitate reviews from other translators who will only look at the Netlify preview of my PR.

Perfect, and almost the same [as the builds use](https://github.com/w3c/wai-media-guide/blob/master/netlify.toml#L2)

> Actually the local navigation.yml file was part of the initial commit [098dbc8](https://github.com/w3c/wai-media-guide/commit/098dbc8909b07cb8674c55023eee58a7a2059289)

Yeah. Yatil changed how things works several times as the site grew, so things vary between repos. I think the 3 possible reasons still apply though. Or do you have another?

**Comment by SteveALee** [comment]
@shawna-slh are you happy for this to be merged?

**Comment by remibetin** [comment]
> Yeah. Yatil changed how things works several times as the site grew, so things vary between repos. I think the 3 possible reasons still apply though. Or do you have another?

No, I don't see another reason, and in the end, the shared version seems to be used in production.

**Comment by shawna-slh** [comment]
Thank you Rémi and Steve!

**Comment by shawna-slh** [comment]
>I can think of 3 possible explanations for having a local navigation.yml rather than using the latest shared version via the data submodule
>* a simple bug
>* was used for local dev but accidentality committed
>* is supposed to diverge from the shared version - but this will soon get out of date.

> @shawna-slh let me know if you'd like me to look at this issue for all repos some time soon.

Yes, please, Steve, thanks! I'm guessing either 1 or 2.

**Pull request merged**
